# BEGIN_KITTY_THEME
# Base2Tone Lavender Dark
include current-theme.conf
# END_KITTY_THEME

font_family SF Mono
font_size 11

background_opacity 0.9

shell_integration enabled
copy_on_select yes

cursor_trail 8
cursor_trail_decay 0.05 0.3
cursor_blink true
